### ISSUE TITLE
Select JSON response returned from POST

### ISSUE THREAD

**Issue by starkey-01** [danieldotnl/ha-multiscrape#101]
## Configuration

```yaml
multiscrape:
  - resource: https://www.url.com/file.js
    scan_interval: 3600
    name: scrape_item
    method: POST
    payload: "properties%5B_uuid%5D=123&properties%5B_linkedLineItemUuid%5D=369&properties%5B_suggestion%5D=&properties%5B_maxQty%5D=5&properties%5B_freightPrice%5D=&properties%5B_productGroup%5D=&id=123&quantity=1"
    log_response: True
    sensor:
      - unique_id: scrape_price_item
        name: Price of Item
        select: "*"
        value_template: '{{ value.price | float/100 }}'
```

## Describe the bug

I am using multiscrape to POST a payload to a JS script which returns a JSON object like below (shortened for this issue). I would like to extract the "price" attribute from this JSON object. Is this possible with multiscrape? Multiscrape sensor requires a CSS selector, what should this be if the entire response is a JSON object. I thought `select: "*"` and `value.price` would work but it isn't.

Am I missing a text to JSON step in the `value_template`?

Multiscrape may not be fit for this purpose except it does work up until the extraction so it would be good if I could get this to work without having to use a different integration. 

Thanks! 

## Debug log

page_response_body.txt from multiscrape logs.

```json

{
  "id": 123,
  "quantity": 1,
  "variant_id": 123,
  "key": "123",
  "title": "Text title",
  "price": 123,
  "original_price": 123,
  "discounted_price": 123,
  "line_price": 123,
  "original_line_price": 123,
  "total_discount": 0,
  "discounts": [],
  "sku": "123",
  "grams": 123,
  "vendor": "ABC",
  "taxable": true,
  "product_id": 123,
  "product_has_only_default_variant": true,
  "gift_card": false,
  "final_price": 123,
  "final_line_price": 123,
  "url": "/url"
}


```
