### ISSUE TITLE
Using resource_template at startup of home assistant there are not important errors in log

### ISSUE THREAD

**Issue by Metus88** [danieldotnl/ha-multiscrape#103]
## Version of the custom_component
v5.7.0
## System Health

version | core-2022.3.8
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v7l+
arch | armv7l
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3957
Installed Version | 1.24.1
Stage | running
Available Repositories | 1006
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 19
views | 24
mode | storage

</details>

## Configuration

```yaml
sensor:
  - platform: file
    file_path: /config/filestatisensori/linkautoletturagas.txt
    name: link gas da file

multiscrape:
  - resource_template: "{{ states('sensor.link_gas_da_file')}}"
    scan_interval: 3600
    name: letture date gas
    sensor:
      - unique_id: fai_la_lettura_del_gas_dal
        name:  Fai la lettura del gas dal
        select: 'script[type="text\/plain"]'
        value_template: "{{ (value | regex_findall_index('data_da..............', index=0)).split('\"')[-2].strip()  }}"
      - unique_id: fai_la_lettura_del_gas_al
        name:  Fai la lettura del gas al
        select: 'script[type="text\/plain"]'
        value_template: "{{ (value | regex_findall_index('data_a..............', index=0)).split('\"')[-2].strip()  }}"
```

## Describe the bug

During the startup of home assistant there are Errors in log that tell that the "resource_template" is not a link like http or https.
How you can see from my configuration.yaml I use a sensor file where  inside the txt file is wrote the url link.
I don't know if it's possible to add a "delay" (standard or editable from the user) during the startup for the component/sensor OR a waiting template.  
Is not a big problem. Maybe there is already a solution that I don't know.
However also with this log info/error it works great... so thanks a lot for your fantastic component!

## Debug log

```text

2022-04-01 22:21:19 ERROR (MainThread) [custom_components.multiscrape.scraper] Error fetching data: unknown failed with Request URL is missing an 'http://' or 'https://' protocol.
2022-04-01 22:21:19 ERROR (MainThread) [custom_components.multiscrape.scraper] Unable to parse response.
2022-04-01 22:21:19 WARNING (MainThread) [homeassistant.components.sensor] Platform multiscrape not ready yet: Request URL is missing an 'http://' or 'https://' protocol.; Retrying in background in 30 seconds


```
