### ISSUE TITLE
on_error issue, triggers my event all the times.

### ISSUE THREAD

**Issue by malosaa** [danieldotnl/ha-multiscrape#110]
i'm using last update and HASS OS 7.5

The thing what i have is that on_error is not working, or i'm doing something wrong.

So this is the thing,

1. it scrapes every let say 10 minutes.
SOmetimes the scrape comes back with an empty value.. 
2. i have setup a automation that, using trigger entity> attribute>above 0

So when the script fails and then have a success it triggers my event all the time.. how can i solve this.

I checked my log and before it happens it returns (none) to all sensors/attributes

```

multiscrape:
  - resource: http://
    scan_interval: 300
    verify_ssl: false
    sensor:
        name: sysmic_activity
        picture: "/local/sysmic.png"
        select: "description:nth-child(1) >text"
        attributes:
          - name: Time
            select: "creationInfo > creationTime"
            on_error:
              value: last
          - name: Magnitude
            select: "mag> value"
            value_template: '{{ value | round(1) }}'
            on_error:
              value: last
          - name: Depth
            select: "depth >value"
            on_error:
              value: last
          - name: city
            select: "description:nth-child(1) >text"
            on_error:
              value: last
          - name: address
            select: "description:nth-child(1) >text"
            on_error:
              value: last
          - name: latitude
            select: "latitude> value"
            on_error:
              value: last
          - name: longitude
            select: "longitude> value"
            on_error:
              value: last
```

event trigger part

```
platform: numeric_state
entity_id: sensor.sysmic_activity
above: '0'
attribute: magnitude
```
