### ISSUE TITLE
Removal of Index from the config broke my sensors

### ISSUE THREAD

**Issue by namadori** [danieldotnl/ha-multiscrape#111]
## Version of the custom_component

6.2.0

## Configuration

```yaml
multiscrape:
  - resource: https://meteoregionelazio.it/rete/stazione.php?id=RM-139
    scan_interval: 600
    sensor:
      - unique_id: infernetto_hum
        name: Umidità Infernetto
        select: ".dato_grande"
        index: 1
        value_template: '{{ (value.split("%")[0]) }}'
        device_class: "humidity"
        state_class: "measurement"
        unit_of_measurement: "%"
```

## Describe the bug

Removal of Index from the config broke all my sensors. It was a useful feature... now how can I get the same result?

Also, the readme.md still lists Index as a parameter.

**Comment by danieldotnl** [comment]
Have a look at this:

https://stackoverflow.com/questions/13193224/target-the-2nd-instance-of-a-css-class

**Comment by danieldotnl** [comment]
Removed the index attribute now from the readme. Thanks for pointing that out.

**Comment by fabHAgithub** [comment]
> ## Versão do custom_component
> 
> 6.2.0
> ## Configuração
> 
> ```yaml
> multiscrape : 
>    - recurso : https://meteoregionelazio.it/rete/stazione.php?id=RM-139 
>     scan_interval : 600 
>     sensor : 
>        - unique_id : infernetto_hum 
>         name : Umidità Infernetto 
>         select : " .dato_grande " 
>         index : 1 
>         value_template : ' {{ (value.split("%")[0]) }} ' 
>         device_class : " humidade " 
>         state_class : " medição " 
>         unit_of_measurement : " % " 
> ```
> 
> ## Descreva o erro
> 
> A remoção do Index da configuração quebrou todos os meus sensores. Foi um recurso útil... agora como posso obter o mesmo resultado?
> 
> Além disso, o readme.md ainda lista Index como um parâmetro.

I have the same issue here. Is for that I'm not updating the component to new version. Did you solved? please, paste here.

**Comment by SirUli** [comment]
Taking the example from above:

```yaml
select: ".dato_grande"
index: 1
```

Then reading the [link](https://stackoverflow.com/questions/13193224/target-the-2nd-instance-of-a-css-class) of Daniel leads to:

```yaml
select: "tr > td[width="243.3"]:nth-of-type(4) > .dato_grande"
```

The issue on that webpage is that there is no specific indicator for the field that @namadori wanted to have.

Generally the solution is ``:nth-of-type(<number>)`` where number is the previous index number + 1 (since it doesn't start with zero).

**Comment by cavalon** [comment]
> I have the same issue here. Is for that I'm not updating the component to new version. Did you solved? please, paste here.

same thing for me! I scrape from a plain site, that mostly consists of paragraphs <p>, and I need the 17th paragraph - no way (so far) to have this scraped off the site with the new version (in the old version it was just like "select: "p" // index: 17"). The methods mentioned above all do not work...

Can we please have "index" back?

**Comment by danieldotnl** [comment]
Could you provide an example (with config) in which the new approach does not work?

**Comment by cavalon** [comment]
> Could you provide an example (with config) in which the new approach does not work?

sure, here you go (working config as of v5.7.0):

```
multiscrape:
  - resource: https://www.meteoschweiz.admin.ch/home.html?tab=report
    scan_interval: 900
    sensor:
      - name: Report
        select: "p"
        index: 17
```
I like to scrape the line under the title (as ow now "Aktualisiert am Sonntag, 24. April 2022, 16:54 Uhr")

the methods mentioned above do not work, e.g. 
`select: ".p:nth-of-type(n)"`
or
`select: ".p:nth-child(n)"`

also using the "CSS Selector" (from page inspector) does not work, e.g.
`select: "div.tabcontainer:nth-child(1) > section:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > article:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2)"`

But: Maybe (for sure!?), there is a working CSS select statement...?
