### ISSUE TITLE
SSL Error even when skipping SSL verification

### ISSUE THREAD

**Issue by barrycraig** [danieldotnl/ha-multiscrape#139]
## Version of the custom_component

v6.3.2

## Configuration

```yaml

multiscrape:
  - resource: https://m.chargeyourcar.org.uk/chargePoint?bayNo=70968
    scan_interval: 300
    verify_ssl: false
    sensor:
      - unique_id: Charger_Multiscrape
        select: "#mostAvailableStatus"
```

## Describe the bug
SSL cert error even when flagging "verify_ssl: false". Cert on the website seems to be totally valid?

```
Logs

Logger: custom_components.multiscrape.coordinator
Source: custom_components/multiscrape/coordinator.py:79
Integration: Multiscrape scraping component ([documentation](https://github.com/danieldotnl/ha-multiscrape), [issues](https://github.com/danieldotnl/ha-multiscrape/issues))
First occurred: 11:05:48 (2 occurrences)
Last logged: 11:06:36

Scraper_noname_0 # Updating failed with exception: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)

```
