### ISSUE TITLE
Unable to scrape data: 'NoneType' object has no attribute 'select_one'

### ISSUE THREAD

**Issue by sepcol** [danieldotnl/ha-multiscrape#151]
Hey 👋 I'm having some issues scraping some basic data

Unable to scrape data: 'NoneType' object has no attribute 'select_one'. Consider using debug logging and log_response for further investigation.

Contents of multiscrape.yaml:

- resource: https://ironforge.pro/api/servers/classic
  scan_interval: 86400
  log_response: true
  sensor:
  - unique_id: nethergarde_keep_realm_players
    name: Nethergarde keep players
    select: "#content > div.content-main > div.response-info > pre"

Part of the contents of page_response_body.txt:

{"date":1663135200000,"week":68,"values":[{"name":"Benediction","realmType":"PvP","locale":"US","language":"East","total":32820,"alliance":32820,"horde":0,"active":true,"fcm":false,"locked":true}`

So it seems like the call got executed but still something failed and no soup file got created

**Comment by danieldotnl** [comment]
The response is in JSON format, which you cannot scrape with CSS selectors. Try a JSON template like this:
```yaml
multiscrape:
  - name: nethergarde
    resource: https://ironforge.pro/api/servers/classic
    scan_interval: 86400
    log_response: true
    sensor:
      - unique_id: nethergarde_keep_realm_players
        name: Nethergarde keep players
        value_template: "{{ value_json['values'][0]['total'] }}"
```
