### ISSUE TITLE
Add attribution to sensor attributes

### ISSUE THREAD

**Issue by kaizersoje** [danieldotnl/ha-multiscrape#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Could you add the ability to set `attribution` for a sensor?

**Describe alternatives you've considered**

**Additional context**

**Comment by kaizersoje** [comment]
Here is a screenshot of a sensor with `attribution` as one of the attributes.

![image](https://user-images.githubusercontent.com/54566217/210869952-305f5b76-31f9-44ce-93ea-8f4699e4d125.png)

This is how it appears on the `more-info` dialog.

![image](https://user-images.githubusercontent.com/54566217/210870085-353f9cc1-df41-49eb-a6ff-abc9dfed127f.png)

When I added the `attribution` attribute to this sensor, I got the error below.

```yaml
multiscrape:
  - name: K-Index
      resource: https://sws-data.sws.bom.gov.au/api/v1/get-k-index
      method: POST
      scan_interval: 10800
      headers:
        Content-Type: application/json
      payload: '{ "api_key": "a7e83c-a7e83ca7e83c-a7e83c-a7e83c", "options": {"location": "Sydney"}}'
      sensor:
        - unique_id: melbourne_k_index
          name: Melbourne K-Index
          icon: mdi:theme-light-dark
          value_template: >
            {% if( value_json.data == []) %}NA
            {% else %}{{ value_json.data[0].index }}{% endif %}
          attributes:
            - name: analysis_time
              value_template: "{{ value_json.data[0].analysis_time }}"
            - name: valid_time
              value_template: "{{ value_json.data[0].valid_time }}"
            - attribution: "Data obtained from the Space Weather Services section of the Australian Bureau of Meteorology"
```

```
Invalid config for [multiscrape]: [attribution] is an invalid option for [multiscrape]. Check: multiscrape->multiscrape->3->sensor->0->attributes->2->attribution. (See ?, line ?).
```
