### ISSUE TITLE
Weird /r when scraping list

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#189]
# Version of the custom_component
6.6.1

## Configuration

```yaml
- name: in-počasi Praha
  resource: "https://www.in-pocasi.cz/predpoved-pocasi/cz/praha/praha-324/"
  scan_interval: 300
  log_response: false
  sensor:
    - unique_id: inpo_praha_forecast_test
      select: ".alfa"
      value_template: "{{(value|trim)[:-2]|float}}"
      attributes:
        - name: "rain"
          select_list: ".h-100 .text-nowrap:nth-child(3)"
          value_template: "{{value.replace('\r','').replace('\n','').replace(' ','').replace('mm','')}}"
Add your logs here.
```

## Describe the bug
For some reason scraping the list into the attribute seems to generate a whole bunch of whitespace and /r/n, which I can partially remove with the .replace, but some sort of `/r,/r` separator always remains.

When I look at this in the template editor
``` 
{{state_attr('sensor.inpo_praha_forecast_test','rain')}}
```
it looks ok, but when I try to paste it here into the github issue box -- I get the carriage returns around each number. I can't find a way of cleanly removing these \r to generate a clean list. When I try by doing
```
{{state_attr('sensor.inpo_praha_forecast_test','rain').split('\r,\r')|map('float')|list}}
```
it prints ok in the template editor, but when actually pasted into a sensor, it always contains the \r.
```
No errors seem to be generated though.

#Expected behaviour: 
The scrape should not include the \r\n codes.
