### ISSUE TITLE
Multiscrape stopped working when previous repo version replaced with HACS version

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#19]
## Version of the custom_component

3.0.1

## Configuration
This is just an excerpt
```yaml
sensor:
  - platform: multiscrape
    resource: https://www.wunderground.com/dashboard/pws/IPRAGU342?cm_ven=localwx_pwsdash
    scan_interval: 300
    selectors:
      wu_dejvice_status:
        name: WU Dejvice Status
        select: "#inner-content > section:nth-child(2) > div:nth-child(1) > div > div > div > div > div.dashboard__title.ng-star-inserted > div > span:nth-child(2)"
        value_template: "{{ value|lower }}"
      wu_dejvice_temperature:
        name: WU Dejvice Temperature
        select: "#inner-content > section:nth-child(2) > div:nth-child(1) > div > div > div > div > div:nth-child(2) > div > lib-tile-current-conditions > div > div.module__body > div > div.small-4.columns.text-left.conditions-temp > div.main-temp > lib-display-unit > span > span.wu-value.wu-value-to"
        unit_of_measurement: °C
        value_template: "{{'%0.1f'|format((float(value)-32)/1.8)}}"
```

## Describe the bug

This was working fine under the multiscrape from the previous repository. I've uninstalled that one and installed the HACS version and now all my multiscrape sensors fail. 

## Debug log

```text
Logger: homeassistant.config
Source: config.py:849
First occurred: 9:06:37 (5 occurrences)
Last logged: 9:06:47

Platform error: sensor - Integration 'multiscrape' not found.
```
