### ISSUE TITLE
Can you use Multiscrape to scrape info from 2 or more URLs? I tried adding another name: section but it didnt seem to work

### ISSUE THREAD

**Issue by haggertyg** [danieldotnl/ha-multiscrape#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by danieldotnl** [comment]
Yes, you can just add the config multiple times like this:

```
- sensor:
  - platform: multiscrape
    name: home assistant scraper
    resource: https://www.home-assistant.io
    selectors:
      version:
        name: Current version
        select: '.current-version > h1:nth-child(1)'
        value_template: '{{ (value.split(":")[1]) }}'
      releasedate:
        name: Release date
        select: '.release-date'
  - platform: multiscrape
    name: home assistant scraper 2
    resource: https://www.home-assistant.io
    selectors:
      version:
        name: Current version2
        select: '.current-version > h1:nth-child(1)'
        value_template: '{{ (value.split(":")[1]) }}'
      releasedate:
        name: Release date2
        select: '.release-date'
```
