### ISSUE TITLE
Scraping not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [danieldotnl/ha-multiscrape#213]
## Version of the custom_component

6.50
## Configuration

```yaml
Add your logs here.
multiscrape:
  - resource: https://www.metrotrains.com.au/
    name: Train Status
    scan_interval: 3600
    sensor:
      - unique_id: werribee_line_status
        name: Werribee Line Status
        select: "#healthboard-line-97 > a > span.status"
        icon: mdi:train
```

## Describe the bug

The scan interval for this sensor is set to every hour. However, as per the last change date on the entity, it shows over 14 hours ago.

![image](https://github.com/danieldotnl/ha-multiscrape/assets/54566217/1fbca10d-5ec5-4416-808b-e5eab18513d1)

Even when I call the `multiscrape.trigger_train_status`, it does not update the sensor. The sensor gets updated when I call the reload service or HA restarts.

## Debug log

```text

Add your logs here.

```
