### ISSUE TITLE
Warning when parsing XML page

### ISSUE THREAD

**Issue by Sjorsa** [danieldotnl/ha-multiscrape#220]
## Version of the custom_component
6.7.1

## Configuration

```yaml
multiscrape:
  - resource: http://10.0.0.20:12321/device/dev4f7137224093c0940000
    name: PRO X Wireless
    scan_interval: 60
    sensor:
      - name:                 Sjors Muis Battery Level
        unique_id:            sjors_muis_battery_level
        icon:               mdi:mouse
        select:               "battery_percent"
        unit_of_measurement:  "%"
        value_template:       '{{ value.split(",")[0] }}'
```

## Describe the bug

When using this integration to parse an XML page, it gives this warning.

## Debug log

```text
2023-07-11 10:48:54.233 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.11/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.


```
