### ISSUE TITLE
Add support for dictionaries and lists in attributes

### ISSUE THREAD

**Issue by mekaneck** [danieldotnl/ha-multiscrape#235]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to access parts of a single attribute within HA

**Describe the solution you'd like**
I'd like the attributes of multiscrape sensors to support dictionaries and lists. Currently the data shows up as text. 

**Describe alternatives you've considered**
Separate sensors for each dictionary entry

**Additional context**
The following two sensors are created with attribute data which should consist of dictionary and list data:

```yaml
multiscrape:
  - name: Multiscrape Date Test
    resource_template: http://date.jsontest.com
    scan_interval: 36000
    sensor:
      - unique_id: multiscrape_date_test
        name: Multiscrape Date Test
        value_template: "{{ value_json.start_date }}"
        attributes:
          - name: test
            value_template: >
              {% set myList = [1,2,3, "4th list item"] %}
              {{ {"key1": "value1", "key2": "value2", "keylist": myList} }}
template:
  - sensor:
      - name: Template Date Test
        unique_id: template_date_test
        state: "ok"
        attributes:
          test: >
            {% set myList = [1,2,3, "4th list item"] %}
            {{ {"key1": "value1", "key2": "value2", "keylist": myList} }}
```
In developer tools:
`{{ state_attr('sensor.multiscrape_date_test','test').keylist[3] }}` results in an error `UndefinedError: 'str object' has no attribute 'keylist'`
But yet:
`{{ state_attr('sensor.template_date_test','test').keylist[3] }}` results in `4th list item`
