### ISSUE TITLE
when multiscrape cant find its select

### ISSUE THREAD

**Issue by VinistoisR** [danieldotnl/ha-multiscrape#24]
If the sensor is trying to scrape a div that isn't there, it breaks all the other sensors as well. 

example:

```
  - platform: multiscrape
    name: home assistant scraper
    resource: https://www.tides.gc.ca/eng/station?sid=4422
    scan_interval: 30
    selectors:
    
      firsthightidetime:
        name: First High Tide
        select: "div.stationTables > div.grid-12.indent-medium > div:nth-child(1) > table > tbody > tr:nth-child(1) > td.time"

      secondhightidetime:
        name: Second High Tide
        select: "div.stationTables > div.grid-12.indent-medium > div:nth-child(1) > table > tbody > tr:nth-child(3) > td.time"

```
some days don't have the second high or second low, so the last cell of the table doesn't exist.  The result is:

```
This error originated from a custom integration.

Logger: custom_components.multiscrape.sensor
Source: custom_components/multiscrape/sensor.py:149
Integration: multiscrape (documentation, issues)
First occurred: May 24, 2021, 11:08:26 PM (1827 occurrences)
Last logged: 2:30:18 PM

Sensor Second Low Tide was unable to extract data from HTML
```
and also

![image](https://user-images.githubusercontent.com/36953653/119571191-e702d080-bd65-11eb-9c87-ce8e2e6d31f9.png)

How can I check for this in advance?  Is there a way to let one sensor fail and keep the others?
