### ISSUE TITLE
Form not found, shadowroot problem?

### ISSUE THREAD

**Issue by marcinbauer85** [danieldotnl/ha-multiscrape#250]
## Version of the custom_component
6.7.3

## Configuration

```yaml
multiscrape:
  - resource: "https://app.usertesting.com/my_dashboard/available_tests_v3"
    scan_interval: 20
    timeout: 30
    log_response: true
    form_submit:
      submit_once: true
      resubmit_on_error: true
      resource: "https://app.usertesting.com/participants/sign_in"
      select: ".ng-untouched .ng-pristine .ng-invalid"
      input:
        email: x
        password: x

    sensor:
      - unique_id: ut_tests
        name: Number of tests
        select: "head > title"
        value_template: "{{ (value) }}"
```

## Describe the bug
Im trying to setup a script to see how many usertesting.com tests are available for me, but Im getting an error when trying to submit the form in order to login to my dashboard.
Maybe its because the form on the login site is in the shadowroot?

## Debug log
```text
This error originated from a custom integration.

Logger: custom_components.multiscrape.coordinator
Source: custom_components/multiscrape/coordinator.py:75
Integration: Multiscrape scraping component (documentation, issues)
First occurred: 11:57:10 AM (9 occurrences)
Last logged: 12:00:00 PM

Scraper_noname_0 # Exception in form-submit feature. Will continue trying to scrape target page. Could not find form
```
