### ISSUE TITLE
Question about Scraping a Table

### ISSUE THREAD

**Issue by Kijan** [danieldotnl/ha-multiscrape#254]
## Version of the custom_component
6.7.3

## Configuration

```yaml
multiscrape:
  - resource: "https://ge-hsw.de"
    scan_interval: 600
    log_response: true
    form_submit:
      submit_once: True
      select: "body > div > main > div > div.panel-body > form"
      input:
        _username: ******
        _password: "*****"
    sensor:
      - select: "#timetable-content-combined > thead > tr > th:nth-child(2) > div.timetable-header-date"
        name: Stundenplan
```

## Describe

So i got the login working but then the new webpage is an empty table.
It should be a timetable for my daughters school.
As i loaded the site in browser, I saw, that the table is empty first and then the data get inserted.
Then i looked at the source the data is also empty. But when i inspect the data is there. 
So is there a way to get those data?
