### ISSUE TITLE
Add prelogin feature

### ISSUE THREAD

**Issue by jonastaedcke** [danieldotnl/ha-multiscrape#26]
Hey Daniel

I‘d like your work and have some sites that need a login before I can get the needed information. 
Would it be possible to add the prelogin feature https://github.com/drogfild/hass-multiscrape to your branch?

**Comment by danieldotnl** [comment]
Please check out [this post](https://community.home-assistant.io/t/scrape-sensor-improved-scraping-multiple-values/218350/73?u=danieldotnl). Would be great if you can test it.

**Comment by jonastaedcke** [comment]
It's great! Worked really really great and I added nine sensors :D

**Comment by jonastaedcke** [comment]
I use four separated instance to set this nine sensors. They all use the same website but with different credentials. After the first refresh the four instance use the first login credential – and all sensors have the values of this first instance.

Maybe it's necessary to use `submit_once: false`. I'll test it :) 

```
- resource: "https://www.website.xx/member.php"
  scan_interval: 3600
  form_submit:
    submit_once: true
    resource: "https://www.website.xx/login"
    select: "#form_login"
    input:
      login_email: !secret email
      login_password: !secret password
  sensor:
    - select: "#path-to-text a:nth-child(1) a"
      name: website-1
- resource: "https://www.website.xx/member.php"
  scan_interval: 3600
  form_submit:
    submit_once: true
    resource: "https://www.website.xx/login"
    select: "#form_login"
    input:
      login_email: !secret email2
      login_password: !secret password2
  sensor:
    - select: "#path-to-text a:nth-child(1) a"
      name: website-2
```
