### ISSUE TITLE
add icon or icon template to the sensors.

### ISSUE THREAD

**Issue by DimkaInc** [danieldotnl/ha-multiscrape#29]
Do you ever plan to add icons to sensors, better icon templates?
Because now, after creating sensors, you have to create sensor templates and only add icons there. 

```
multiscrape:
  - resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - name: Latest version
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) }}'
      - name: Release date
        select: ".release-date"
    binary_sensor:
      - name: Latest version == 2021.7.0
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) | trim == "2021.7.0" }}'

sensor:
  - platform: template
    sensors:
      latest_version_good:
         friendky_name: Latest version
         value_template: '{{ states('sensor.latest_version') }}'
         icon_template: >-
             {% if is_state('sensor.latest_version', states('sensor.version')) %}
                 mid:movie-star-outline
             {% else %}
                 mid:history
             {% end if %}

binary_sensor:
  - platform: template
    sensors:
       latest_version_good:
          friendly_name: Latest version
          value_template: '{{ is_state('binary_sensor.latest_version', 'on') }}'
          icon_template: >-
             {% if is_state('binary_sensor.latest_version', 'on') %}
                mid:check-circle-outline
             {% else %}
                mid:checkbox-blank-circle-outline
             {% end if %}

```
After that, duplicate sensors appear with and without icons.

**Comment by danieldotnl** [comment]
Can't you achieve this already by setting the appropriate device_class on the sensor?

**Comment by DimkaInc** [comment]
Forgive my ignorance in this matter, but where can I get acquainted with the creation of a custom device_classes?

**Comment by danieldotnl** [comment]
Here is the list you can provide with the sensor in multiscrape config: https://www.home-assistant.io/integrations/binary_sensor#device-class

**Comment by DimkaInc** [comment]
> 
> 
> Here is the list you can provide with the sensor in multiscrape config: https://www.home-assistant.io/integrations/binary_sensor#device-class

Maybe I was incorrectly said. Among the existing device_classes no matter what I need, and I asked how to make a custom device_classes?

**Comment by danieldotnl** [comment]
Please check pre-release v4.1.0!

**Comment by DimkaInc** [comment]
Thanks for the promptness, but it doesn't work very well.
That is, it either works only once, or sets the icon from the block else and does not change it. 

This code throws an error:
```
  multiscrape:
    - resource: !secret pwr_sw_address
      username: !secret pwr_sw_username
      password: !secret pwr_sw_password
      scan_interval: 5
      sensor:
        - name: relay_1
          select: "button[name=relayon1] ~ img"
          attribute: "src"
          value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
          icon: >- #-<
            {% if value.split("light")[1].split(".jpg")[0] == 'on' %}
              hass:electric-switch-closed
            {% else %}
              hass:electric-switch
            {% endif %}

```
Log error:

```
 Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:72
Integration: Template (documentation, issues)
First occurred: 17:58:19 (1 occurrences)
Last logged: 17:58:19
TemplateError('UndefinedError: 'value' is undefined') while processing template 'Template("{% if value.split("light")[1].split(".jpg")[0] == 'on' %} hass:electric-switch-closed {% else %} hass:electric-switch {% endif %}")' for attribute '_icon' in entity 'sensor.relay_1'

```

This code throws no errors, but sets the icon from the block else. At the same time, I tried to use the same value_template, old_state instead of new_state 

```
  multiscrape:
    - resource: !secret pwr_sw_address
      username: !secret pwr_sw_username
      password: !secret pwr_sw_password
      scan_interval: 5
      sensor:
        - name: relay_1
          select: "button[name=relayon1] ~ img"
          attribute: "src"
          value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
          icon: >- #-<
            {% if new_state == 'on' %}
              hass:electric-switch-closed
            {% else %}
              hass:electric-switch
            {% endif %}

```

This code is triggered only once, switching from on to off, and then writes in the log that a loop has been detected. 

```
  multiscrape:
    - resource: !secret pwr_sw_address
      username: !secret pwr_sw_username
      password: !secret pwr_sw_password
      scan_interval: 5
      sensor:
        - name: relay_1
          select: "button[name=relayon1] ~ img"
          attribute: "src"
          value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
          icon: >- #-<
            {% if is_state('sensor.relay_1', 'on') %}
              hass:electric-switch-closed
            {% else %}
              hass:electric-switch
            {% endif %}

```

Log:

```
 Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:241
Integration: Template (documentation, issues)
First occurred: 18:21:28 (1 occurrences)
Last logged: 18:21:28
Template loop detected while processing event: <Event state_changed[L]: entity_id=sensor.relay_1, old_state=<state sensor.relay_1=off; friendly_name=relay_1, icon=hass:electric-switch @ 2021-06-15T18:21:18.170341+03:00>, new_state=<state sensor.relay_1=on; friendly_name=relay_1, icon=hass:electric-switch @ 2021-06-15T18:21:28.197983+03:00>>, skipping template render for Template[{% if is_state('sensor.relay_1', 'on') %} hass:electric-switch-closed {% else %} hass:electric-switch {% endif %}]

```

The very ability to add an icon is great! You are cool!

**Comment by danieldotnl** [comment]
Thanks for your appreciation. Don't forget to [buy me a coffee](https://www.buymeacoffee.com/danieldotnl) ;)

I'm using the same code as the template sensor, therefore you cannot use the value from the value_template but should make a full reference to the sensor.
I'll look into the loop. I'm afraid I didn't test it with a reference to it's own sensor.

**Comment by DimkaInc** [comment]
Nothing has changed in this release. But, Imho that it is more correct to set the icon in accordance with the selected value, and not with the self-check of the status. This way you can avoid looping. 

```
multiscrape:
    - resource: !secret pwr_sw_address
      username: !secret pwr_sw_username
      password: !secret pwr_sw_password
      scan_interval: 5
      sensor:
        - name: relay_1
          select: "button[name=relayon1] ~ img"
          attribute: "src"
          value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
          icon: >-
            {% if value.split("light")[1].split(".jpg")[0] == 'on' %}
              hass:electric-switch-closed
            {% else %}
              hass:electric-switch
            {% endif %}

```

**Comment by danieldotnl** [comment]
This seems to be related and unresolved in core home assistant: https://github.com/home-assistant/core/issues/42003

**Comment by DimkaInc** [comment]
> 
> 
> This seems to be related and unresolved in core home assistant: [home-assistant/core#42003](https://github.com/home-assistant/core/issues/42003)

And closed as stale [home-assistant/core#42003](https://github.com/home-assistant/core/issues/42003#issuecomment-765897305)

**Comment by danieldotnl** [comment]
Yes and therefore I'm a bit stuck. I didn't try it yet, but I think I can easily implement your suggestion to use the value which is output from the select or the value_template. 
However, I'm not sure if that is what everybody expects and I don't like that it then works different than in the template sensor integration....

Maybe it's the best thing to do though, risking a breaking change in the future if template loop is fixed in the template sensor.

**Comment by DimkaInc** [comment]
I opened that Issue again [home-assistant/issues#9439](https://github.com/home-assistant/frontend/issues/9439)

**Comment by danieldotnl** [comment]
Dmirty, could you check release pre-v4.1.3? I implemented using the value output from the sensor value_template.
So this should work:

```yaml
multiscrape:
    - resource: !secret pwr_sw_address
      username: !secret pwr_sw_username
      password: !secret pwr_sw_password
      scan_interval: 5
      sensor:
        - name: relay_1
          select: "button[name=relayon1] ~ img"
          attribute: "src"
          value_template: '{{ value.split("light")[1].split(".jpg")[0] }}'
          icon: >-
            {% if value == 'on' %}
              hass:electric-switch-closed
            {% else %}
              hass:electric-switch
            {% endif %}
```

You can still make a full self-reference to the sensor (sensor.relay_1), but then it will use the previous value as the sensor is not yet updated at the moment the icon is set.

I'm curious what you think of it!
