### ISSUE TITLE
Unique ID is an invalid option

### ISSUE THREAD

**Issue by drthanwho** [danieldotnl/ha-multiscrape#32]
## Version of the custom_component 
v4.0.1

## Configuration
```yaml
multiscrape:
  - resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - unique_id: 197410fe-726e-45b2-b758-6050bd55c6a9
        name: Latest version
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) }}'
      - unique_id: 3d2e81ba-3e45-42e2-bfad-d5543609ef0a
        name: Release date
        select: ".release-date"
    binary_sensor:
      - name: Latest version == 2021.6.0
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) | trim == "2021.6.0" }}'
```

## Describe the bug

Simply adding the provided example or any other configuration results to the error. Unique ID is not a valid option
```
Invalid config for [multiscrape]: [unique_id] is an invalid option for [multiscrape]. Check: multiscrape->multiscrape->1->sensor->1->unique_id. (See /config/configuration.yaml, line 51).
```

## Debug log

```text

N/A
```

**Comment by danieldotnl** [comment]
Sorry, I have already updated the README for the pre-release v4.1.0.
For the stable release, please use this example:

```yaml
multiscrape:
  - resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - name: Latest version
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) }}'
      - name: Release date
        select: ".release-date"
    binary_sensor:
      - name: Latest version == 2021.7.0
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) | trim == "2021.7.0" }}'
```
