### ISSUE TITLE
attribute names are not well-formed

### ISSUE THREAD

**Issue by kongo09** [danieldotnl/ha-multiscrape#33]
## Version of the custom_component

pre-4.1.1

This is a follow-on issue to #27 

## Configuration

```yaml
# Dell Printer
multiscrape:
  - resource: !secret printer_status
    scan_interval: 900
    sensor:
      - name: Printer Toner Level Cyan
        select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(2) > td:nth-child(1) > b"
        value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False) }}'
        unit_of_measurement: "%"
      - name: Printer Toner Level Magenta
        select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(4) > td:nth-child(1) > b"
        value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False) }}'
        unit_of_measurement: "%"
      - name: Printer Toner Level Yellow
        select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(6) > td:nth-child(1) > b"
        value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False) }}'
        unit_of_measurement: "%"
      - name: Printer Toner Level Black
        select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(8) > td:nth-child(1) > b"
        value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False) }}'
        unit_of_measurement: "%"
      - name: Printer Toner Level
        select: "body > table > tr > td > table:nth-child(10) > tr > td > table > tr:nth-child(2) > td:nth-child(2) > b"
        unit_of_measurement: "%"
        attributes:
          - name: Cyan Toner
            select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(2) > td:nth-child(1) > b"
            value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False)|int }}'
          - name: Magenta
            select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(4) > td:nth-child(1) > b"
            value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False)|int }}'
          - name: Yellow
            select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(6) > td:nth-child(1) > b"
            value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False)|int }}'
          - name: Black
            select: "body > table > tr > td > table:nth-child(6) > tr > td > table > tr:nth-child(8) > td:nth-child(1) > b"
            value_template: '{{ value|regex_findall_index(find="(\d+)\%", index=0, ignorecase=False)|int }}'
```

## Describe the bug

Attribute names are not well-formed, i.e.
* they are not converted to all lower case
* spaces are not converted to underscore

In the example above, the attribute named `Cyan Toner` will not show up as an attribute `cyan_toner` in the sensor, which is what I would expect:

![image](https://user-images.githubusercontent.com/640121/122257790-9ef04d00-ced0-11eb-8c41-08bb0bde3ca6.png)
