### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by glibg10b** [danieldotnl/ha-multiscrape#330]
I'm using multiscrape to check if this year's bursary application at my university is open. Within two hours of it opening, a notification is sent to my phone.

The login form looks like this:

![image](https://github.com/danieldotnl/ha-multiscrape/assets/56197853/20df0f6a-0d8c-492f-b8fe-7d58075eb35c)

I examined the POST request body, as your documentation suggested. I had to enable "Persist Logs" in the Network tab so the logs wouldn't disappear after the redirect:

```yaml
userid_placeholder: u12345678
password: REDACTED
foilautofill:
request_id: -6445261644565702005
OAM_REQ: 
username: 12345678
```

The page to be parsed is behind a button and some javascript that doesn't change the page URL. However, I was able to isolate the source page by using the URL in the button div's href.

![image](https://github.com/danieldotnl/ha-multiscrape/assets/56197853/4d96dd67-2508-46bc-abdc-839ef3004b1c)

```yaml
multiscrape:
  - name: UP bursary payout scraper
    log_response: True
    resource: 'https://upnet.up.ac.za/psc/pscsmpra_newwin/EMPLOYEE/SA/c/UP_SF_FL_MENU.UP_OL_PAY_SSF_FL.GBL?NavColl=true'
    scan_interval: 7200
    form_submit:
      submit_once: True
      resource: 'https://www1.up.ac.za/uplogin/faces/login.jspx?<some stuff>'
      select: "form#login_form"
      input:
        username: 12345678
        userid_placeholder: u12345678
        password: REDACTED
    sensor:
      - unique_id: payoutdates
        name: UP bursary payout dates
        select_list: ".ps_grid-flex > .ps_grid-body > tr > td:nth-child(3) > div > span"
```

The result is `2023`. It should change to `2023,2024` or `2024,2023` when the new application becomes available.

Thank you for making this possible (and easy)!
