### ISSUE TITLE
Logger not reporting Debug logs

### ISSUE THREAD

**Issue by Erudition** [danieldotnl/ha-multiscrape#336]
I have this in my config, but I still was not getting debug logs:
```yaml
# set log levels
logger:
  default: info
  logs:
    custom_components.multiscrape: debug
```

...only info and warnings. It turns out I had to modify this file:
https://github.com/danieldotnl/ha-multiscrape/blob/master/custom_components/multiscrape/manifest.json

to add a `loggers` line:

```json
{
  "domain": "multiscrape",
  "name": "Multiscrape scraping component",
  "codeowners": ["@danieldotnl"],
  "config_flow": false,
  "dependencies": [],
  "documentation": "https://github.com/danieldotnl/ha-multiscrape",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/danieldotnl/ha-multiscrape/issues",
  "requirements": ["lxml>=4.9.1", "beautifulsoup4>=4.12.2"],
  "version": "6.5.0",
  "loggers": ["custom_components.multiscrape"]
}
```
