### ISSUE TITLE
Add default value if element not available

### ISSUE THREAD

**Issue by kristjanbjarni** [danieldotnl/ha-multiscrape#34]
I am selecting value from a very dynamic page and some of the time some values are not included in the HTML. This results in a very ugly error in the log "Sensor {name} unable to extract data from HTML" and a value of unknown for the sensor.

What I would like to have is to have some kind of default value to be used when the data can not be extracted or at least some way of hiding the error from the log with some option. When there multiple sensor the log gets a lot of false errors.

**Comment by danieldotnl** [comment]
I don't find the errors "very ugly", i think they are actualy quite straight-forward. I'm considering to downgrade them to warnings though. Would that help?

I'm not sold on default values yet..

**Comment by kristjanbjarni** [comment]
Having this as warnings would be better, but having an option to suppress any errors/warnings for a sensor would be even better, since these are not errors just simply missing information at the specified time. The problem is the CSS select language just isn't very flexible to handle missing information.

**Comment by stevehop** [comment]
I second the request for a default value in the event that an element is unavailable and/or the ability to supress the warnings. One of my scrapes is for my local weather from the BBC site and everyday at 5pm they remove the low temperature element from the page which means that every 30 minutes until midnight I have the "unable to extract data error" in the log. I feel that in a situation such as this, with a dynamic element, there should be an option to handle this.

**Comment by stevehop** [comment]
@danieldotnl thanks for implementing the on_error option so quickly, I've just tested it and am finding that it's still throwing up errors for the attributes of the sensor having missing scrape values.
```
2021-08-15 08:01:46 ERROR (MainThread) [custom_components.multiscrape.entity] Sensor CashConverters Product #1 attribute price was unable to extract data from HTML
2021-08-15 08:01:46 ERROR (MainThread) [custom_components.multiscrape.entity] Sensor CashConverters Product #1 attribute delivery was unable to extract data from HTML
2021-08-15 08:01:46 ERROR (MainThread) [custom_components.multiscrape.entity] Sensor CashConverters Product #1 attribute alert was unable to extract data from HTML
```
My sensor is setup to scrape form a user input URL in a text field and 99% of the time will be empty, I have an automation that manually runs the scrape only when the URL text field is populated. However multiscrape is giving errors when it's reloaded. You can see from my config below that I've set "log = false" but it looks like this doesn't cover the scraping of the attributes, only the main sensor itself. In fact splitting the attributes into their own separate sensors confirms this, they don't generate errors and correctly set their state as "unknown"

```
-   resource_template: '{% set url = states("input_text.cashconverters_product_1") %}{% if url == "" %}http://127.0.0.1{% else %}{{url}}{% endif %}'
    name: cashconverters_product#1_scrape
    scan_interval: 86400
    sensor:
      - unique_id: multiscrape_cconvprod1
        name: 'CashConverters Product #1'
        on_error:
            value: none
            log: false
        select: "span.block:nth-child(1)"
        attributes:
          - name: 'price'
            select: ".product-details__price"
          - name: 'delivery'
            select: ".product-details__postage > div:nth-child(2) > p:nth-child(1)"
            value_template: '{{ (value.split(":")[1]).split("days – ")[1] }}'
          - name: 'alert'
            select: ".product-details__status"
```

**Comment by stevehop** [comment]
@danieldotnl I have just tested the on_error option and it's working well, thanks for sorting that so quickly

**Comment by danieldotnl** [comment]
@kristjanbjarni could you confirm as well that it solves the issue?

**Comment by kristjanbjarni** [comment]
> 
> 
> @kristjanbjarni could you confirm as well that it solves the issue?

Yes tested this and works very well. This is great. Thank you 👍

**Comment by danieldotnl** [comment]
Released now in v5.5.0

**Comment by zenguru84** [comment]
hey @danieldotnl!

I know this is old, but maybe I get lucky.
I try to get the info from a <span>, but sometimes that span is replaced with <bold> containing 2 dashes (no value for now).
So, the scrapping process fails.

On the sensor I use:

on_error:
        log: false
        value: default
        default: "N/A"

But the sensor is no longer created after the restart. If I replace value: default with value: none, the sensor is created with unavailable state.

Am I doing something wrong?

**Comment by stevehop** [comment]
> But the sensor is no longer created after the restart. If I replace value: default with value: none, the sensor is created with unavailable state.
> 
> Am I doing something wrong?

The only difference between yours and mine (that works) is my use of single quotation marks around the default value

```
on_error:
  value: default
  log: false
  default: '-'
```
