### ISSUE TITLE
v7 doesnt work when v6.8.1 was with form submit - get 401/406 on form_page

### ISSUE THREAD

**Issue by sphen13** [danieldotnl/ha-multiscrape#346]
Just updated to 7.0 and my multiscrape is no longer working. I am trying to debug as best as possible but I am a bit lost.

config:
```
multiscrape:
  - resource: 'https://app.smartoilgauge.com/ajax/main_ajax.php'
    log_response: True
    method: POST
    payload: 'action=get_tanks_list&tank_id=0'
    headers:
      X-Requested-With : XMLHttpRequest
      Content-Type : application/x-www-form-urlencoded
    scan_interval: 3600
    form_submit:
      submit_once: False
      resource: 'https://app.smartoilgauge.com/login.php'
      select: ".content-container"
      input:
        username: xxxxx
        user_pass: 'xxxxx'
    sensor:
      - name: smartoiltank
        unique_id: smartoiltank
        value_template: '{{ value_json.tanks[0].sensor_gallons }}'
        unit_of_measurement: "gal"
        attributes:
          - name: tank_name
            value_template: '{{ value_json.tanks[0].tank_name }}'
          - name: last_updated_time
            value_template: '{{ value_json.tanks[0].sensor_rt }}'
          - name: last_updated_timestamp
            value_template: '{{ value_json.tanks[0].last_read }}'
          - name: battery
            value_template: '{{ value_json.tanks[0].battery }}'
```

what i notice is that in 7.0 the `form_page_request_body.txt` actually has data:
```
action=get_tanks_list&tank_id=0
```
while in 6.8.1 it only has `None`. I am not sure if that is why the login page is failing.

I then get no `_soup` file and no cookie within the `form_page_response_headers.txt`

is there a way to not send the `payload` to the login form?

for now rolling back to 6.8.1

fyi this is the error response on the form load:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>Not Acceptable</h1>
<p>An appropriate representation of the requested resource could not be found on this server.</p>
<p>Additionally, a 406 Not Acceptable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
