### ISSUE TITLE
Service doesn't exist after upgrade

### ISSUE THREAD

**Issue by dcmeglio** [danieldotnl/ha-multiscrape#348]
## Version of the custom_component 
7.0.0

## Configuration

```yaml
multiscrape:
  - resource_template: >
      https://untappd.com/b/id/{{ states("sensor.kegtron_kt_100_94d7_port_name") }}
    name: tap_1
    scan_interval: 86400
    sensor:
      - unique_id: keg_tap1_name
        name: Keg Tap 1 Name
        select: ".name > h1:nth-child(1)"
      - unique_id: keg_tap1_brewery
        name: Keg Tap 1 Brewery
        select: ".name .brewery > a:nth-child(1)"
        on_error:
            value: last
  - resource_template: >
      https://untappd.com/b/id/{{ states("sensor.kegtron_kt_200_93f5_port_name_port_1") }} 
    scan_interval: 86400
    name: tap_2
    sensor:
      - unique_id: keg_tap2_name
        name: Keg Tap 2 Name
        select: ".name > h1:nth-child(1)"
      - unique_id: keg_tap2_brewery
        name: Keg Tap 2 Brewery
        select: ".name .brewery > a:nth-child(1)"
        on_error:
            value: last
  - resource_template: >
      https://untappd.com/b/id/{{ states("sensor.kegtron_kt_200_93f5_port_name_port_2") }} 
    name: tap_3
    scan_interval: 86400
    sensor:
      - unique_id: keg_tap3_name
        name: Keg Tap 3 Name
        select: ".name > h1:nth-child(1)"
      - unique_id: keg_tap3_brewery
        name: Keg Tap 3 Brewery
        select: ".name .brewery > a:nth-child(1)"
        on_error:
            value: last
```

## Describe the bug

On 6.8.1 this was working and created 3 services I could call from my automations, I used to have `multiscrape.trigger_tap_1` , `multiscrape.trigger_tap_2`, and `multiscrape.trigger_tap_3` which I could call. Since updating to 7.0.0 only `multiscrape.trigger_tap_3` exists

## Debug log

Enabled debug logging, I do not see anything in the logs, the 2 services just don't seem to get created any longer.
