### ISSUE TITLE
Help! scrape a text inside span

### ISSUE THREAD

**Issue by Bellavista** [danieldotnl/ha-multiscrape#373]
Can someone help me! I can't extract the text.... i tryed tryed tryed.....    i don't ideas!
thank you

![image](https://github.com/danieldotnl/ha-multiscrape/assets/46230198/719f81df-564c-4ea7-a701-f9aebe9693d7)

```
         - name: Descrizione pioggia a video valore
            select: "#h23-27-1 > td.col7 > span#c5a-43008........."
            on_error:
              log: false
              value: default
              default: "Nan"
          - name: Descrizione pioggia hdata valore
            select: "#h23-27-1 > td.col7 > span.hdata.........."
            on_error:
              log: false
              value: default
              default: "Nan"
```
