### ISSUE TITLE
Is the form submitted ? why not?

### ISSUE THREAD

**Issue by screem20056** [danieldotnl/ha-multiscrape#392]
## Configuration

```yaml
multiscrape:
    resource: https://www.ideco.com.jo/portal/WebForms/SubscriberReceivableLinks.aspx
    log_response: true
    name: 'ideco'
    scan_interval: 3600
    form_submit:
      submit_once: True
      resource: "https://www.ideco.com.jo/portal/WebForms/SubscriberReceivableLinks.aspx"
      select: "#ContentPlaceHolder1_Panel1"
      input:
        'ctl00$ContentPlaceHolder1$txtCustomerNo': '0120019332'
        'ctl00$ContentPlaceHolder1$btnGetInvoices2': ''
      input_filter:
      - 'ctl00$ContentPlaceHolder1$ddlCities'
      - '#__EVENTTARGET'
      - 'div.aspNetHidden:nth-child(9)'
      - 'div.aspNetHidden:nth-child(1)'
      - '#__EVENTARGUMENT'        
      - '#__EVENTVALIDATION'
    sensor:
      - unique_id: IDECO
        name: IDECO
        select: "#ContentPlaceHolder1_txtCustomerNo"
        value_template: "{{ value | trim }}"
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Add your logs here.
```

## Describe the bug

i really spent so much time trying to find out what is the issue and trying different combination from different soultion mentioned by others but no hope.
I wonder if you can help me get this to work. It is basically my electricity supplier website where I simply want to know when a new invoice is issued for my account, which I mentioned in the YAML code 0120019332.
for some reason, the selector I put for the sensor, which is my account number, is empty while it should show my account number, as after submission, the number remains, for me I think this is a clue that the form was not submitted in the first place, which i can not understand at all.
## Debug log
all is fine as the sensor was able to scrape with empty results, if i change the selector to the month number which i wont then i got a message saying that the tag of the selector is not available which make sense as the form was not submitted correctly 

```text

Add your logs here.

```
