### ISSUE TITLE
Unable to create working trend helper from scraped sensor

### ISSUE THREAD

**Issue by Taomyn** [danieldotnl/ha-multiscrape#418]
## Version of the custom_component

7.2.0

## Configuration

```
    sensor:
      - unique_id: guichet_95_fuel_price
        device_class: monetary
        state_class: measurement
        name: 95 Fuel Price
        icon: mdi:gas-station
        value_template: "{{ value_json['items'][0]['Price95Fuel'] }}"
        unit_of_measurement: "€"
```

## Describe the bug

When I try to create a trend helper from my sensor, there is no attribute for data and so the trend is always empty

I also reported it to the HA Core github hoping it was an issue on their side seeing as it's a new feature and it's the only thing not seeing the data: https://github.com/home-assistant/core/issues/121287
