### ISSUE TITLE
Unable to parse response

### ISSUE THREAD

**Issue by bradgyton** [danieldotnl/ha-multiscrape#44]
Hey

Trying to parse the date for my next bin collection. Tried a few varying configurations but all are failing with "Unable to parse response"

I'm able to make a simple curl request or postman request to this site and a response is returned. No authentication or custom headers are required.

have also tried with the older `parser: html.parser`

## Configuration

```yaml
multiscrape:
  - resource: https://wasteservices.sheffield.gov.uk/property/100051011212
    scan_interval: 86400
    sensor:
      - unique_id: bins_black_nextcollection
        name: Next Black Bin Collection
        select: "#main > div.container.results-table-wrapper > div:nth-child(1) > div > table > tbody > tr.service-id-1.task-id-1.complete > td.next-service"
        value_template: '{{ (value.split(",")[1]) }}
```

## Error/Logs

```
2021-08-04 20:48:08 ERROR (MainThread) [custom_components.multiscrape.data] Error fetching data: https://wasteservices.sheffield.gov.uk/property/100051011212 failed with
2021-08-04 20:48:08 ERROR (MainThread) [custom_components.multiscrape.data] Unable to parse response.
```
