### ISSUE TITLE
Add capability to include multi-scraped sensor in statistics graph

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#45]
**Is your feature request related to a problem? Please describe.**
Currently, scraped sensors are not considered `measurements` by HA and therefore long-term data are not collected. This means that one cannot make long-term plots on the new statistics graph card. I scrape a whole bunch of numerical data into HA and it would be great to be able to look at long-term trends.

**Describe the solution you'd like**
It would be great if it were possible to set a property for a sensor such that HA would collect statistics on it, according to the spec [here](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics).

**Describe alternatives you've considered**
Extending the database  is not really an option beyond some 10s of days and is completely unnecessary for most cases.

**Comment by danieldotnl** [comment]
Yeah, I'm already looking into this after yesterday's 2021.8 release

**Comment by wigster** [comment]
Hi

I’ve upgraded to 5.3.0dev and have added the state_class attribute to a couple of numerical scrapers but they do not appear in the sensors I can pick for a ststistics plot

```
state_class: measurement
unit_of_measurement: °C
friendly_name: WU Dejvice Temperature
```

but maybe you are not ready to announce this yet.

**Comment by danieldotnl** [comment]
Hi, it works for me:
![image](https://user-images.githubusercontent.com/2983203/128606794-9ba3321d-0797-4f83-b4ab-47c723bf8d59.png)

Could you share your full config?

**Comment by stevehop** [comment]
Same trouble here

```
-   resource: https://www.bbc.co.uk/weather/2656955
    name: bbc_weather_scrape
    scan_interval: 1800
    sensor:
      - unique_id: multiscrape_test
        name: multiscrape_test
        select: "#daylink-13 > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > span:nth-child(2) > span:nth-child(1) > span:nth-child(1)"
        state_class: measurement
        unit_of_measurement: '°C'
```

**Comment by danieldotnl** [comment]
It works when you add a device_class:

```
- resource: https://www.bbc.co.uk/weather/2656955
    name: bbc_weather_scrape
    scan_interval: 1800
    sensor:
      - unique_id: multiscrape_test
        name: multiscrape_test
        select: "#daylink-13 > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > span:nth-child(2) > span:nth-child(1) > span:nth-child(1)"
        state_class: measurement
        device_class: temperature
        unit_of_measurement: '°C'
        value_template: '{{ (value.split("°")[0]) }}'
```

I didn't know that was a requirement and I think it's a bit strange, but that's a question for home assistant core.
