### ISSUE TITLE
Multiscrape Entities Not Created When Product Data is Missing

### ISSUE THREAD

**Issue by jlipsit** [danieldotnl/ha-multiscrape#466]
Hoping someone can help. I posted on other sites but did not get any advice. 

I’m using the multiscrape integration in Home Assistant to scrape product data from SmartLabel website, based on a UPC stored in the sensor.esphome_web_e0bdc0_barcode_scanner_data sensor. The problem arises when I restart Home assistant: If the previous UPC in the sensor points to a valid page, but the product data isn’t found (e.g., the expected elements don’t exist on the page) **then the multiscrape entities (e.g., sensor.smartlabel_product_title, sensor.smartlabel_product_image) are not created.** 

This becomes a major issue after restarting Home Assistant, as the entities remain "unknown" or completely missing, which breaks further scanning and related automations.

Goal:
I want to ensure the multiscrape entities are always created at startup, even if the scraped data is missing or unavailable. Ideally, these entities should initialize with a default state (e.g., "Product Not Found"). If this isn’t officially supported, I’m looking for a reliable workaround to achieve this. 

multiscrape:
  - resource_template: "https://smartlabel.syndigo.com/upc/{{ states('sensor.esphome_web_e0bdc0_barcode_scanner_data') | default('041415033658') }}"
    scan_interval: 86400
    sensor:
      - name: "SmartLabel Product Title"
        unique_id: "smartlabel_product_title"
        select: "title"
      - name: "SmartLabel Product Image"
        unique_id: "smartlabel_product_image"
        select: "img.top__image"
        attribute: "src"
      - name: "SmartLabel Supermarket Name"
        unique_id: "smartlabel_supermarket_name"
        select: "div.medium-medium"

If not, what’s the best workaround to address this?  I can help pay if this functionality can be added to multiscrape. It would be very useful for others as well.

**Comment by jlipsit** [comment]
With the help of ChatGPT I figured this out.  Works great now!  I will leave this for others who might need the help.  :-)
```
multiscrape:
  - name: "SmartLabel"
    resource_template: "https://smartlabel.syndigo.com/upc/{{ states('sensor.esphome_web_e0bdc0_barcode_scanner_data') | default('041415033658') }}"
    scan_interval: 86400
    sensor:
      - name: "SmartLabel Product Title"
        unique_id: "smartlabel_product_title"
        select: "title"
        on_error:
          value: default
          default: "Not Found"
          log: false

      - name: "SmartLabel Product Image"
        unique_id: "smartlabel_product_image"
        select: "img.top__image"
        attribute: "src"
        on_error:
          value: default
          default: "Not Found"
          log: false

      - name: "SmartLabel Supermarket Name"
        unique_id: "smartlabel_supermarket_name"
        select: "div.medium-medium"
        on_error:
          value: default
          default: "Not Found"
          log: false

```
