### ISSUE TITLE
Unable to scrape website (page_soup.txt shows the value needed)

### ISSUE THREAD

**Issue by luisgarcia87** [danieldotnl/ha-multiscrape#467]
## Version of the custom_component

v8.0.4

## Configuration

```yaml
  - resource: 'http://consultasaldomb.com:8080/PortalCAE-WAR-MODULE/SesionPortalServlet?accion=6&NumDistribuidor=99&NomUsuario=usuInternet&NomHost=AFT&NomDominio=aft.cl&Trx=&RutUsuario=0&NumTarjeta=17267339&bloqueable='
    name: Metro Blanca Saldo
    scan_interval: 60
    log_response: true
    sensor:
      - select: 'body > table > tr:nth-child(2) > td > table > tr:nth-child(1) > td:nth-child(2) > table > tr > td > table > tr:nth-child(3) > td > table > tr > td > table > tr:nth-child(2) > td:nth-child(2)'
        name: metro_panama_saldo_tarjeta_blanca_2
```

## Describe the bug

I can't get the value from the website. On the debug files on the page_soup.txt and on the page_response_body.txt I can see the value in HTML but I am not able to retrieve it. I've also read [this guide](https://github.com/danieldotnl/ha-multiscrape/wiki/Scraping-guide): And removed all the original tbody elements but still the value does not show. Is it posssible to obtain the value by changing the selector perhpahs?

Thanks

## Debug log

```text

Logger: custom_components.multiscrape.sensor
Source: custom_components/multiscrape/sensor.py:159
integration: Multiscrape ([documentation](https://github.com/danieldotnl/ha-multiscrape), [issues](https://github.com/danieldotnl/ha-multiscrape/issues))
First occurred: 12:00:59 PM (15 occurrences)
Last logged: 12:16:24 PM

Metro Blanca Saldo # metro_panama_saldo_tarjeta_blanca_2 # Unable to scrape data: Could not find a tag for given selector Consider using debug logging and log_response for further investigation.

```
