### ISSUE TITLE
Add `last_reset` to sensor options in YAML configuration

### ISSUE THREAD

**Issue by adam-t-b** [danieldotnl/ha-multiscrape#487]
### Problem Statement ###
In some cases, data consumed from scraping is for a previous point in time. In these moments, scraping the data and setting it as a sensor value will show as inaccurate in Home Assistant. An example of this is with `watersmart.com`. It's easy to pull JSON data from their site, but they only update data on the following day. So, updating a sensor in HA will always be 24hrs offset.

### Idea ###
The`total` `state_class` does not require `last_reset` to be set, but does allow it [optionally](https://developers.home-assistant.io/docs/core/entity/sensor/#how-to-choose-state_class-and-last_reset). Using this we could backdate data as needed.

#### Example API Response From WaterSmart####
```
{
  "data": {
    "chartData": {
      "mode": "ami",
      "dailyData": {
        "categories": [
          "2025-02-23",
          "2025-02-24",
          "2025-02-25"
        ],
        "consumption": [
          225.3,
          276.6,
          125.3
        ],
        "temperature": [
          27.375,
          32.625,
          40.9583,
          35.8333
        ],
        "precipitation": [
          0,
          0,
          18.3999996185
        ],
      }
    }
  }
}
```
#### Example YAML to set Last Reset ####
```
  sensor:
    - name: "Water Daily Consumption"
      unique_id: "water_daily_consumption"
      device_class: "water"
      force_update: true
      state_class: "total"
      unit_of_measurement: "gal"
      value_template: "{{ value_json.data.chartData.dailyData.consumption | last }}"
      last_reset: "{{ value_json.data.chartData.dailyData.categories | last }}T12:00:00"
      icon: "mdi:cup-water"
```

### Alternatives ###
I've explored different options but miltiscrape was the best method for authenticating. I've tried storing the JSON and then reading it via some othe r scripting, but it's a hack. I honestly don't see any other way of achieving this cleanly.
