### ISSUE TITLE
Preserve sensor state after HA restart

### ISSUE THREAD

**Issue by andreypolyak** [danieldotnl/ha-multiscrape#62]
**Is your feature request related to a problem? Please describe.**
I have two sensors set up with ha-multiscrape:
```yaml
- name: Katya Yandex Rain State
  resource_template: URL_HERE
  scan_interval: 120
  headers: 
    user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
  sensor:
    - unique_id: katya_yandex_rain_state
      name: Katya Yandex Rain State
      select: div.weather-maps-fact__nowcast-alert
      on_error:
        value: last
      value_template: >
        {{ (value.split(".")[1]) }}

- name: Katya Home to Work Commute State
  resource_template: URL_HERE
  scan_interval: 120
  headers: 
    user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
  sensor:
    - unique_id: katya_home_to_work_commute_state
      name: Katya Home to Work Commute State
      select: div.auto-route-snippet-view__route-title-primary
      unit_of_measurement: min
      on_error:
        value: last
      value_template: >
        {% if "мин" in value and "ч" in value %}
          {{ value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int * 60 +
            value|regex_findall_index(find="\d+.", index=1, ignorecase=False)|int }}
        {% elif "ч" in value %}
          {{ value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int * 60 }}
        {% elif "мин" in value %}
          {{ value|regex_findall_index(find="\d+.", index=0, ignorecase=False)|int }}
        {% else %}
          unavailable
        {% endif %}
```

They both work fine with one exception: after Home Assistant restart they have their values lost. The first sensor has "unknown" state, second -- "1" state.

**Describe the solution you'd like**
I would like to have sensors that will preserve their state after HA restart.
