### ISSUE TITLE
Resource offline

### ISSUE THREAD

**Issue by theOrakle** [danieldotnl/ha-multiscrape#65]
**Is your feature request related to a problem? Please describe.**
I have an IOT that is not online but every once in a while.

**Describe the solution you'd like**
I would like the capability to quieting logs when the resource is offline and use the on_error to still have the entities default to a value.

**Describe alternatives you've considered**
On_error doesn't take effect when the resource in unreachable

**Additional context**
None

**Comment by txespirito** [comment]
I have the same problem as theOrakle, but with a peculiarity.
Like theOrakle, on_error doesn't take effect when the resource in unreachable, but in my case if I do different scrape
![scrape](https://user-images.githubusercontent.com/65449504/147815363-2decc3fb-d347-4931-81a2-aed44582c463.png)
 queries for different sensors it is always available, but if I group the queries with multiscrape the sensors are not available intermittently. In the image I put an example with the two forms.

**Comment by danieldotnl** [comment]
Could you guys check the behavior on release v6.2.0?

**Comment by theOrakle** [comment]
I still see this in the logs:

```
2022-04-24 21:25:31 ERROR (MainThread) [custom_components.multiscrape.http] Scraper_noname_0 # Error executing get request to url: http://bbq.bla-bla.local.
 Error message:
 ConnectError('All connection attempts failed')
```

There is a possibility I do not the on error configured correctly, but given how easy it is, I would be surprised:
 ```
    on_error:
      log: false
      value: default
      default: 0
```

**Comment by StevenBrs** [comment]
Hi All,

I have the same issue reading out the values of my solar panels. The inverter is only online when powered by the sun.
I tried adding on_error, but this doesn't work and the entities are marked as "Unavailable".

```
multiscrape:
  - name: Solis WiFi Scraper
    resource: ******
    authentication: basic
    username: ******
    password: ******
    scan_interval: 60
    sensor:
      - unique_id: solis_1_webdata_now_p
        name: Current Power (W)
        icon: mdi:solar-power
        unit_of_measurement: "W"
        select: "script:nth-of-type(2)"
        value_template: "{{ (value | regex_findall('webdata_now_p = \"(.*)\";', true))[0]|int }}"
        force_update: true
        on_error:
          value: default
          default: 0
        attributes:
        - name: "Solis S/N"
          value_template: "{{ (value | regex_findall('webdata_sn = \"(.*)\";', true))[0] }}"
      - unique_id: solis_1_webdata_today_e
        name: Yield Today (kWh)
        icon: mdi:solar-power
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy
        select: "script:nth-of-type(2)"
        value_template: "{{ (value | regex_findall('webdata_today_e = \"(.*)\";', true))[0]|float }}"
        force_update: true
        on_error:
          value: none
        attributes:
        - name: "Solis S/N"
          value_template: "{{ (value | regex_findall('webdata_sn = \"(.*)\";', true))[0] }}"
        - name: last_reset
          value_template: "{{ now().strftime('%Y-%m-%dT00:00:00') }}"
```
