### ISSUE TITLE
Add the ability to add    entity_picture: 

### ISSUE THREAD

**Issue by malosaa** [danieldotnl/ha-multiscrape#70]
First of all this multiscrape is so awsome!!!!

Well when i'm scraping and sometimes its a geolocation of a car or police or wathever, i want it to show the picture on the map, without doing it manually.

Now it shows the first letter of the device i just scraped on my map, and no way to add a picture.

like adding this to my scrape as an attribute, but won't let me 

 entity_picture: "/local/test.jpg"

this is how i scrape now 

```
sensor:
        name: sysmic_activity_italy
        select: "description:nth-child(1) >text"
        attributes:
          - name: Time
            select: "creationInfo > creationTime"
          - name: Magnitude
            select: "mag> value"
          - name: Latitude
            select: "lat> value"
          - name: Longitude
            select: "lat> value"
```

it shows the correct location on the map but with a big round S, because the name starts with sysmic.
With entity_picture:  it will show up a picture instead, just like an person.

regards and keep this project up !!
