### ISSUE TITLE
CAN'T REPLACE THE SIGNAL ' --- SINGLE QUOTES

### ISSUE THREAD

**Issue by fabHAgithub** [danieldotnl/ha-multiscrape#85]
EDIT: SOLV THE PROBLEM TO MY OWN!
Just need to use these lines [have a great day all :))))]:

```
      - unique_id: zoo_brasilia_imagem_6
        icon: mdi:elephant
        name: Zoo de Brasília - Img 6
        select: '.img-destaque'
        attribute: 'style'
        value_template: 'https://www.zoo.df.gov.br/{{value.split(".")[4] | replace("br/","")}}.jpg' #png
        #'https://www.zoo.df.gov.br/{{value.split("/")[3]}}/{{value.split("/")[4]}}/{{value.split("/")[5]}}/{{value.split("/")[6]}}/{{value.split("/")[7] | replace (")","") | replace(".jpg", ".jpg                                               ")}}' 
        #'https://www.zoo.df.gov.br{{value.split("https://www.zoo.df.gov.br")[1] | replace(")", "") }}'
        #'{{value.split(" ")[1] | replace("(", "") | replace(")", "") | replace(";", "") | replace("url", "") }}'
        #'{{ value.split("*")[0] | replace("g')", "g") | replace("background-image: ", "") | replace("url('h", "h") }}'
        #'{{value.split(" ")[1] | replace("(", "") | replace(")", "") | replace(";", "") | replace("url", "") }}'
        #'{{value.split(" ")[1] | replace("(", " ") | replace(")", " ") | replace(";", " ") | replace("url", " ") }}'
```

I need the url from image without the single quotes to put the link from multiscrape intro my generic cameras, but when I scrape e replace all the useless things I got this template with the 2 single quotes:

![image](https://user-images.githubusercontent.com/85220859/151098963-f192c01a-5d1f-4314-b40e-b0f11b4d2edd.png)

my scrape sensor that return value with 2 single quotes:
`### ZOO DE BRASÍLIA ###`
```
  - resource: https://www.zoo.df.gov.br/
    scan_interval: 3600
    sensor:
      - unique_id: zoo_brasilia_imagem_7
        icon: mdi:elephant
        name: Zoo de Brasília - Img 7
        select: '.img-destaque'
        attribute: 'style'
        index: 1
        value_template: '{{value.split(" ")[1] | replace("(", "") | replace(")", "") | replace(";", "") | replace("url", "") }}'
```

sensor with problem when I try to remove the quotes:
![image](https://user-images.githubusercontent.com/85220859/151100287-4ba604fc-5146-47ca-9dbb-d5463c9f2bf3.png)
`### ZOO DE BRASÍLIA ###`
```
  - resource: https://www.zoo.df.gov.br/
    scan_interval: 3600
    sensor:
      - unique_id: zoo_brasilia_imagem_6
        icon: mdi:elephant
        name: Zoo de Brasília - Img 6
        select: '.img-destaque'
        attribute: 'style'
        value_template: '{{value.split("*")[0] | replace("g')", "g") | replace("background-image: ", "") | replace("url('h", "h") }}'
```

log problem:
can not read an implicit mapping pair; a colon is missed at line 228, column 117:
     ... ground-image: ", "") | replace("url('h", "h") }}'
                                         ^

humble request: can I get the sensor without that 2 single quotes in the image?
please, don't close iit I think it's simple.. help me s2
