### ISSUE TITLE
Log response is an invalid option for multiscrape

### ISSUE THREAD

**Issue by starkey-01** [danieldotnl/ha-multiscrape#94]
## Configuration

```yaml
logger:
  default: info
  logs:
    custom_components.multiscrape: debug

multiscrape:
  - resource: https://url.com/
    scan_interval: 3600
    log_response: True
    sensor:
      - unique_id: scrape_price
        name: Price of Item
        select: "#ProductSection- > div > div.one-quarter > div.product-cta > div.pricing-block > div > span"
        value_template: '{{ (value.split("$")[1]) | float }}'
  - resource: ...
```

## Describe the bug

When checking configuration, Home Assistant returns an error that log_response is an invalid option for multiscrape. I tried restarting with just logger block first and log_response commented out. HA still says it is an invalid option when uncommenting after restart.

Am I specifying log_response incorrectly?

```
Invalid config for [multiscrape]: [log_response] is an invalid option for [multiscrape]. Check: multiscrape->multiscrape->0->log_response. (See /config/configuration.yaml, line 166).
```

## Debug log

```text

Can't include as I can't enable.

```
