### ISSUE TITLE
Auto-create sensors based on select_list

### ISSUE THREAD

**Issue by YeonV** [danieldotnl/ha-multiscrape#99]
First of all THANK YOU SOO MUCH for this nice project!

**Is your feature request related to a problem? Please describe.**
Manually setting a sensor for each list-item can be exhausting.
Also its problematic if the list is changing.

**Describe the solution you'd like**
Auto- create and remove sensors based on `select_list`
maybe add a `list_item` key next to `select_list` to define `name`, `select` and `attribute` for all items.
Note: `name` should accept a `select`-string here.

**Additional context**
Maybe it would be convinient to have all `select`-strings inside `list_item` scoped to the element:

```mermaid
flowchart TB
A[select_list: li.item] -->|Getting 3 list items| B(list_item)
B -->| item1 | D[Sensor 1]
B -->| item2 | E[Sensor 2]
B -->| item3 | F[Sensor 3]
```

```yml
  - resource: XXX
    scan_interval: 3600
    sensor:
      - unique_id: XXXX
        name: Items
        select_list: "li.item"
        value_template: |
          {%-set value = value.split(",")-%}
          {{value|count}}
        list_items:
          name: "h2"                            # Should be working like `li.item[i] h2`
          select: ".details > .magicValue"      # Should be working like `li.item[i] .details > .magicValue`
          value_template: "{{ value|int }}"
          attributes:
            - name: Other Value
              select: ".details > .otherValue"  # Should be working like `li.item[i] .details > .otherValue`
```
